# Change these first
owner: simplegr # Your GitHub organization or username, where this repository lives
repo: simple-uptime-status # The name of this repository

sites:
  - name: Simple (GR)
    url: https://www.simplewebsolutions.gr
  - name: Verum Coffee
    url: https://www.verumcoffee.gr
  - name: In Deep Analysis
    url: https://indeepanalysis.gr
  - name: MMC Group Holding Hellas
    url: https://www.mmcgroupholding.com
  - name: Mosfero
    url: https://www.mosfero.com
  - name: Regal Hotel
    url: https://www.regalhotels.gr
  - name: Santorini Best Tours (EN)
    url: https://santorinibesttours.com
  - name: Telmaco
    url: https://www.telmaco.gr
  - name: Δήμος Τρίπολης
    url: https://www.tripolis.gr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
